# Predictive Modeling (Regression) - House Price Prediction

This notebook builds regression models to predict house prices. We split the dataset into training and testing sets, train multiple models, evaluate performance using MSE and R², and compare results.

In [10]:

!pip install -q gdown

import gdown
import pandas as pd

file_id = "1sCwQC0sgRMsBYJijlGBheTrY5dQel7P4"

gdown.download(
    f"https://drive.google.com/uc?id={file_id}",
    "dataset.csv",
    quiet=False
)

df = pd.read_csv("dataset.csv")
df.head()

Downloading...
From: https://drive.google.com/uc?id=1sCwQC0sgRMsBYJijlGBheTrY5dQel7P4
To: /content/dataset.csv
100%|██████████| 49.1k/49.1k [00:00<00:00, 44.6MB/s]

  0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0   0.02731   0.00   7.070  0  0.4690  6.4210  78...
1   0.02729   0.00   7.070  0  0.4690  7.1850  61...
2   0.03237   0.00   2.180  0  0.4580  6.9980  45...
3   0.06905   0.00   2.180  0  0.4580  7.1470  54...
4   0.02985   0.00   2.180  0  0.4580  6.4300  58...

In [11]:
import pandas as pd

df = pd.read_csv(
    "dataset.csv",
    sep='\s+',
    header=None
)

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (506, 14)

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_2586/1417476610.py:5: SyntaxWarning: invalid escape sequence '\s'
  sep='\s+',

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## Feature and Target Separation

The I divide the dataset into predictor variables (features) and the target variable (house price). I also check for missing values before training machine learning models.

In [12]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nMissing Values in Features:")
print(X.isnull().sum())

print("\nMissing Values in Target:")
print(y.isnull().sum())

Feature Shape: (506, 13)
Target Shape: (506,)

Missing Values in Features:
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

Missing Values in Target:
0

## Train-Test Split

The dataset is divided into training and testing sets. The training set is used to train the model, while the testing set is used to evaluate its performance on unseen data.

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)
print("Training Target Shape:", y_train.shape)
print("Testing Target Shape:", y_test.shape)

Training Features Shape: (404, 13)
Testing Features Shape: (102, 13)
Training Target Shape: (404,)
Testing Target Shape: (102,)

## Linear Regression Model

Train a Linear Regression model and evaluate its performance using Mean Squared Error (MSE) and R-squared (R²).

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print("Linear Regression Results")
print("MSE:", mse_lr)
print("R² Score:", r2_lr)

Linear Regression Results
MSE: 24.291119474973478
R² Score: 0.6687594935356326

## Decision Tree Regression

A Decision Tree Regressor models non linear relationships by recursively splitting the data into smaller subsets.Then evaluate the performance  using Mean Squared Error (MSE) and R-squared (R²).

In [15]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree Results")
print("MSE:", mse_dt)
print("R² Score:", r2_dt)

Decision Tree Results
MSE: 10.416078431372549
R² Score: 0.8579634380978161

## Random Forest Regression

Random Forest is an ensemble method that combines multiple decision trees to improve accuracy and reduce overfitting. It is expected to perform better than a single Decision Tree.

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Results")
print("MSE:", mse_rf)
print("R² Score:", r2_rf)

Random Forest Results
MSE: 7.901513892156864
R² Score: 0.8922527442109116